import Head from 'next/head'; // Importing the Head component from the 'next/head' package
import styles from '../styles/Home.module.css'; // Importing the CSS styles from the 'Home.module.css' file
import { GraphQLClient, gql } from 'graphql-request'; // Importing the GraphQLClient and gql functions from the 'graphql-request' package
import BlogCard from './components/BlogCard'; // Importing the BlogCard component from the './components/BlogCard' file

// Create a new GraphQL client instance with the specified API endpoint
const graphcms = new GraphQLClient('https://api-ap-southeast-2.hygraph.com/v2/clinteyc30jqt01t77ac126mk/master');

// GraphQL query to fetch the required data
const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

// This function is executed at build time to fetch the data needed for the page
export async function getStaticProps() {
  // Send a request to the GraphQL API with the defined query and retrieve the 'posts' data
  const { posts } = await graphcms.request(QUERY);

  return {
    props: {
      posts, // Pass the 'posts' data as a prop to the component
    },
    // Indicates how often the data should be revalidated (in seconds)
    revalidate: 10,
  };
}

// The main component for the home page
export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Little Scribbles</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className='site-title'>Little Scribbles</h1>
        {/* Render each blog post as a BlogCard component */}
        {posts.map((post) => (
          <BlogCard
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  );
}
