import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {GraphQLClient, gqp} from 'graphql-request';

const graphcms = new GraphQLClient('https://api-ap-southeast-2.hygraph.com/v2/clinteyc30jqt01t77ac126mk/master');

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='{styles.main'>

      </main>
    </div>
  );
}